@startuml diagrama

class PatrullaEspiritual
class GranLider
class TazoDorado{
    - Bool flotando
    + Flotar()
}

class Foco

PatrullaEspiritual o-- TazoDorado
GranLider "1" *-- "*" Foco
TazoDorado "1" o-- "*" Foco


@enduml